BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[BackupCode] (
    [id] NVARCHAR(1000) NOT NULL,
    [userId] NVARCHAR(1000) NOT NULL,
    [code] NVARCHAR(1000) NOT NULL,
    [used] BIT NOT NULL CONSTRAINT [BackupCode_used_df] DEFAULT 0,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [BackupCode_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [BackupCode_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- AddForeignKey
ALTER TABLE [dbo].[BackupCode] ADD CONSTRAINT [BackupCode_userId_fkey] FOREIGN KEY ([userId]) REFERENCES [dbo].[User]([id]) ON DELETE CASCADE ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
