BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[User] DROP CONSTRAINT [User_twoFactorEnabled_df];
ALTER TABLE [dbo].[User] ADD CONSTRAINT [User_twoFactorEnabled_df] DEFAULT 1 FOR [twoFactorEnabled];

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
