BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[User] ADD [twoFactorBackupCodes] NVARCHAR(1000),
[twoFactorEnabled] BIT NOT NULL CONSTRAINT [User_twoFactorEnabled_df] DEFAULT 0,
[twoFactorSecret] NVARCHAR(1000);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
